### PR TITLE
Added support for Python 3.x

### PR DESCRIPTION
**Pull request by friedenhe**
## Purpose
Added support for Python 3.x

## Type of change
- New feature (non-breaking change which adds functionality)

## Testing
The DAFoam reg tests that use this repo passed for both Python 3.x and Python 2.7

## Checklist
_Put an `x` in the boxes that apply._

- [x] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Review by sseraj — COMMENTED** [review]
The face normals have already been merged, so I think this PR should only have the Python 3.x commit?

**Comment by friedenhe** [comment]
Yes, it should be just python 3 fixes, but for some reason, it shows two commits... I guess it should be fine.

**Review by sseraj — COMMENTED** [review]
Yes, the file itself looks fine.

Another question: 
Do we only use the byte option for the files we want to compress?

**Comment by friedenhe** [comment]
Yes, that is only needed for .gz files with Python 3.x, and it is also compatible with Python 2.7. For ASCII files, the byte option is not needed and works for both 2.7 and 3.x.

**Review by sseraj — APPROVED** [review]
Thanks for explaining!

**Pull request merged**
